### ISSUE TITLE
Mendix Buildpack incompatible with Azure Service Broker for PostgreSQL

### ISSUE THREAD

**Issue by daniellavoie** [mendix/cf-mendix-buildpack#194]
## Overview

The azure service broker generates a username with `@` characters. The `jdbcUrl` is parsed by the Mendix Buildpack python compile script. Then, it rebuilds a config object

## Problem

The values found in `jdbcUrl` are URI encoded. Values that are configured in the config dictionary for m2e are not supposed to be encoded as a URI format is not expected.

## Fix to implement

The database URL expected by the buildpack must not contain encoded values.  `buildpackutil.lib` should build a URL from the non encoded fields of the credential blob from `VCAP_SERVICES` when an azure postgresql database is identified.

## Workaround

So far, my only workaround was to provision a PostgreSQL on native Azure and rewrite the DATABASE_URL to this format :

`postgresql://{{user}}@{{servername}}:{{password}}@{{db-hostname}}:5432/{{}}?sslmode=require`

This format is not the default one for PostgreSQL or JDBC and is not documented anywhere.

## VCAP Services
``` 
{
  "staging_env_json": {},
  "running_env_json": {},
  "system_env_json": {
    "VCAP_SERVICES": {
      "azure-postgresqldb": [
        {
          "name": "mendgres",
          "instance_name": "mendgres",
          "binding_name": null,
          "credentials": {
            "postgresqlServerName": "u242b03ed",
            "postgresqlDatabaseName": "u5G975c97",
            "postgresqlServerFullyQualifiedDomainName": "u2071b03ed.postgres.database.azure.com",
            "administratorLogin": "u513fea4e1",
            "administratorLoginPassword": "FJc9i15ioeMPnMsCbl7V3tImbZo0BJR5KdqbQb/Z3/5U8CDJajw==",
            "jdbcUrl": "jdbc:postgresql://u207142b03ed.postgres.database.azure.com:5432/u52D5G975c97?user=u513ba4e1%40u207142b03ed&password=FJc9i15ioeMPnMsCbl7V3tImbRoNZo0BJR5KdqbQb%2FZ3%22SVCDJajw%3D%3D&ssl=true",
            "hostname": "u20703ed.postgres.database.azure.com",
            "port": 5432,
            "name": "u52G975c97",
            "username": "u5dfea4e1@u242b03ed",
            "password": "FJc9ioeMPnMV3tImbRoNZo0BJR5KdqbQb/Z3/5U8CDJajw==",
            "uri": "postgres://u513bd4e1%40u202b03ed:FJioeMPnMsCbl7V3tImbRoNZo0BJRbQb%2FZ3%22SVCDJajw%3D%3D@u20b03ed.postgres.database.azure.com:5432/u52D75c97"
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "azure-postgresqldb",
          "provider": null,
          "plan": "basic50",
          "tags": [
            "Azure",
            "PostgreSQL",
            "Database"
          ]
        }
      ]
    }
....
```

## Startup logs

```
2018-08-24T16:17:41.928-04:00 [APP/PROC/WEB/0] [OUT] INFO: Trying to start the MxRuntime...
2018-08-24T16:17:45.098-04:00 [APP/PROC/WEB/0] [OUT] INFO - Logging: Logging to file: /home/vcap/app/log/out.log, max size: 1099511627776KiB, max rotation: 10
2018-08-24T16:17:45.134-04:00 [APP/PROC/WEB/0] [OUT] INFO - Core: Mendix Runtime 7.14.1 (build 34716). Copyright © 2003-2018 Mendix bv. All rights reserved.
2018-08-24T16:17:45.281-04:00 [APP/PROC/WEB/0] [OUT] INFO - M2EE: Setting MaxFormContentSize for Runtime Server to 10485760
2018-08-24T16:17:45.413-04:00 [APP/PROC/WEB/0] [OUT] INFO - Services: Adding 0 authority certificate(s)
2018-08-24T16:17:45.428-04:00 [APP/PROC/WEB/0] [OUT] INFO - metrics: Started metrics on logging
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] Aug 24, 2018 8:17:46 PM org.postgresql.Driver connect
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] SEVERE: Connection error:
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] org.postgresql.util.PSQLException: FATAL: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:438)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.Driver.makeConnection(Driver.java:450)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.Driver.connect(Driver.java:252)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at java.sql.DriverManager.getConnection(DriverManager.java:664)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at java.sql.DriverManager.getConnection(DriverManager.java:247)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:94)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:79)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.dbcp2.DataSourceConnectionFactory.createConnection(DataSourceConnectionFactory.java:44)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:861)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.connections.jdbc.ConnectionManager.getConnection(ConnectionManager.java:49)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.ConnectionBusInitializer.$anonfun$createConnection$1(ConnectionBusInitializer.scala:52)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at scala.util.Try$.apply(Try.scala:209)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.ConnectionBusInitializer.retry(ConnectionBusInitializer.scala:60)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.ConnectionBusInitializer.createConnection(ConnectionBusInitializer.scala:52)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.ConnectionBusInitializer.initialize(ConnectionBusInitializer.scala:42)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.connectionbus.ConnectionBusImpl.initialize(ConnectionBusImpl.java:290)
2018-08-24T16:17:46.448-04:00 [APP/PROC/WEB/0] [ERR] at com.mendix.basis.impl.MxRuntimeImpl.initializeConnectionBus(MxRuntimeImpl.java:474)
```

**Comment by markbastiaans** [comment]
As this issue is more than two years old, we are closing it.

We would be more than happy to revisit it if it is still relevant.
