### ISSUE TITLE
"This script does not work on Python 3.6"

### ISSUE THREAD

**Issue by basi01** [mendix/cf-mendix-buildpack#498]
Today we noticed that the same buildpack version v4.25.0 no longer works.
```
Staging app and tracing logs...
   Cell 3be7cced-2045-4e2b-b82a-960637ef57c5 creating container for instance ebb6109b-81a9-467f-bcde-678ae57fb2fb
   Cell 3be7cced-2045-4e2b-b82a-960637ef57c5 successfully created container for instance ebb6109b-81a9-467f-bcde-678ae57fb2fb
   Downloading app package...
   Downloaded app package (64.4M)
   ---> Mendix Cloud Foundry Buildpack v4.25.0 [development] staging...
   ---> Check if Python dependencies need to be cached...
   ---> Bootstrapping pip...
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
   Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100 2548k  100 2548k    0     0  25.1M      0 --:--:-- --:--:-- --:--:-- 25.1M
   ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
   ---> Downloading Python dependencies...
   /tmp/buildpackdownloads/063299c9588a0e1d380502ed03d75f37/bin/../bin/bootstrap-python: line 67: /home/vcap/.local/bin/pip: No such file or directory
   ---> Installing Python dependencies to /tmp/app/.local/lib/python3.6/site-packages...
   /tmp/buildpackdownloads/063299c9588a0e1d380502ed03d75f37/bin/../bin/bootstrap-python: line 71: /home/vcap/.local/bin/pip: No such file or directory
   ---> Finished installing Python dependencies
   Traceback (most recent call last):
   File "/tmp/buildpackdownloads/063299c9588a0e1d380502ed03d75f37/bin/../buildpack/stage.py", line 7, in <module>
   from buildpack import databroker, util
   File "/tmp/buildpackdownloads/063299c9588a0e1d380502ed03d75f37/buildpack/databroker/__init__.py", line 12, in <module>
   import backoff
   ModuleNotFoundError: No module named 'backoff'
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
```

It seems that it's trying to download "backoff" with pip and pip no longer works with python 3.6.

**Comment by kennyheaton** [comment]
I have been researching this since it is currently blocking us from releasing. Here is what I've found:

Pip, pythons package installer, updated on 1/29/22 to drop support for python 3.6 and now only supports 3.7 and above: https://pip.pypa.io/en/stable/news/#v22-0

The stack included with Cloud Foundry by default is cflinuxfs3 
GitHub: https://github.com/cloudfoundry/cflinuxfs3

cflinuxfs3 comes installed with 3.6 as the version of python3:
https://github.com/cloudfoundry/cflinuxfs3/blob/main/receipt.cflinuxfs3.x86_64#L598

the Mendix Buildpack cf-mendix-buildpack uses python3 when installing pip, which is rejected by pip:
https://github.com/mendix/cf-mendix-buildpack/blob/master/bin/bootstrap-python#L53

This is a blocking issue for us.

**Comment by basi01** [comment]
@kennyheaton The workaround is to use the .zip buildpack. It has a bundled pip .whl
```
  buildpacks:
  - https://github.com/mendix/cf-mendix-buildpack/releases/latest/download/cf-mendix-buildpack.zip
  # or if you want to lock to a certain version 
  #- https://github.com/mendix/cf-mendix-buildpack/releases/download/v4.25.0/cf-mendix-buildpack.zip
```

**Comment by kennyheaton** [comment]
Thank you @basi01

**Comment by svanderburg** [comment]
Maybe this change will fix the problem: https://github.com/mendix/cf-mendix-buildpack/commit/7a8004283423d7f6aadd9281e4929e088ec38a9c

In addition, we typically recommend people to refer to the Zip files of the releases for buildpack deployments, rather than referencing the Git repository. Deploying from release Zip files are typically faster.

**Comment by coonsat** [comment]
Hi,
We're still having problems with our deployment. I've tried to deploy with both:
 https://github.com/mendix/cf-mendix-buildpack/releases/latest/download/cf-mendix-buildpack.zip
and
https://github.com/mendix/cf-mendix-buildpack/releases/download/v4.25.1/cf-mendix-buildpack.zip.
We're no longer getting the original error but a new one:
`2022-02-02T15:37:05.663+01:00 [APP/PROC/WEB/0] [OUT] INFO: Using external file store configured by user-defined settings. See https://github.com/mendix/cf-mendix-buildpack for file store configuration details.

2022-02-02T15:37:05.663+01:00 [APP/PROC/WEB/0] [OUT] DEBUG: Java heap size set to 256M

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] **ERROR: Failed to parse JAVA_OPTS: invalid JSON**

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] Traceback (most recent call last):

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] File "/home/vcap/app/buildpack/core/java.py", line 155, in _set_user_provided_java_options

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] options = json.loads(options)

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/__init__.py", line 354, in loads

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] return _default_decoder.decode(s)

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/decoder.py", line 339, in decode

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] obj, end = self.raw_decode(s, idx=_w(s, 0).end())

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] raise **JSONDecodeError("Expecting value", s, err.value) from None**

2022-02-02T15:37:05.665+01:00 [APP/PROC/WEB/0] [OUT] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] ERROR: Starting application failed. Traceback (most recent call last):

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "buildpack/start.py", line 134, in <module>

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] java.update_config(m2ee, util.get_vcap_data(), java_version)

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "/home/vcap/app/buildpack/core/java.py", line 222, in update_config

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] _set_user_provided_java_options(m2ee)

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "/home/vcap/app/buildpack/core/java.py", line 155, in _set_user_provided_java_options

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] options = json.loads(options)

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/__init__.py", line 354, in loads

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] return _default_decoder.decode(s)

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/decoder.py", line 339, in decode

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] obj, end = self.raw_decode(s, idx=_w(s, 0).end())

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] raise JSONDecodeError("Expecting value", s, err.value) from None

2022-02-02T15:37:05.666+01:00 [APP/PROC/WEB/0] [OUT] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-02-02T15:37:05.670+01:00 [APP/PROC/WEB/0] [OUT] DEBUG: Terminating process group...`

Any idea why this could be happening? I've attempted to try various buildpacks but I get the same error.

**Comment by basi01** [comment]
@coonsat I don't think it's related. Looks like the env var JAVA_OPTS is an empty string although it should be a JSON array of strings. If JAVA_OPTS is in your cf manifest try commenting it. Otherwise try the following

    cf unset-env APP_NAME JAVA_OPTS

**Comment by markbastiaans** [comment]
@coonsat - the Python issue is resolved in the latest release.

The `JAVA_OPTS` error is indeed related to an issue with what's in the env variable, as @basi01 points out. I believe that issue is now picked up with / by Mendix Support.

I'm closing this particular issue. Feel free to reach out via Mendix Support or Github if you encounter any other issues.
