### ISSUE TITLE
Make target generate_software_bom fails with python error

### ISSUE THREAD

**Issue by algotamx** [mendix/cf-mendix-buildpack#578]
Hi guys,

running the make target `generate_software_bom` there is a python `KeyError`.  
(seems like the `mendix-logfilter` in `dependencies.yml` is missing a `version` value)

Stacktrace:

```
Traceback (most recent call last):
  File "buildpack/util.py", line 890, in <module>
    cli()  # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "buildpack/util.py", line 857, in generate_software_bom
    "version": dependency["version"],
KeyError: 'version'
make: *** [Makefile:28: generate_software_bom] Error 1
````

Error Source:  
https://github.com/mendix/cf-mendix-buildpack/blob/master/buildpack/util.py#L857

Dependency:  
https://github.com/mendix/cf-mendix-buildpack/blob/master/dependencies.yml#L55

CF Buildpack version:  
4.30.6

**Comment by jeohist** [comment]
Looks like this was resolved here: https://github.com/mendix/cf-mendix-buildpack/commit/85c67f1beac6d787bd6a8d2b1a0a8f4fbc9d8044
